DROP TABLE IF EXISTS project;
CREATE TABLE project(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	image VARCHAR(255),
	title VARCHAR(255),
	resume TEXT,
	description TEXT,
	link VARCHAR(255)
);

DROP TABLE IF EXISTS language;
CREATE TABLE language(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	title VARCHAR(255),
	logo VARCHAR(255),
	level INT
);

DROP TABLE IF EXISTS technology;
CREATE TABLE technology(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	title VARCHAR(255),
	logo VARCHAR(255)
);

DROP TABLE IF EXISTS theory;
CREATE TABLE theory(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	title VARCHAR(255),
	level INT
);

DROP TABLE IF EXISTS pole;
CREATE TABLE pole(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	title VARCHAR(255),
	value INT,
	color VARCHAR(7),
	highlight VARCHAR(7)
);